git mv chapter-02 chapter-02-emerging-javascript
git mv chapter-03 chapter-03-functional-programming-with-javascript
git mv chapter-04 chapter-04-pure-react
git mv chapter-05 chapter-05-react-with-jsx
git mv chapter-06 chapter-06-props-states-and-the-component-tree
git mv chapter-07 chapter-07-enhancing-components
git mv chapter-08 chapter-08-redux
git mv chapter-09 chapter-09-react-redux
git mv chapter-10 chapter-10-testing
git mv chapter-11 chapter-11-react-router
git mv chapter-12 chapter-12-react-and-the-server
